export * as AuthService from './auth'
export * as StaffService from './staff'
export * as ExcursionsService from './excursions'
export * as HotelsService from './hotels'
export * as ToursService from './tours'
export * as BookingService from './booking'
export * as CustomersService from './customers'
