/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './../routes/__root'
import { Route as PrivateLayoutIndexImport } from './../routes/_private/_layout/index'
import { Route as PrivateLayoutRouteImport } from './../routes/_private/_layout/route'
import { Route as PrivateRouteImport } from './../routes/_private/route'
import { Route as PublicLoginIndexImport } from './../routes/_public/login/index'
import { Route as PublicRouteImport } from './../routes/_public/route'

// Create/Update Routes

const PublicRouteRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRouteRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PrivateLayoutRouteRoute = PrivateLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => PrivateRouteRoute,
} as any)

const PublicLoginIndexRoute = PublicLoginIndexImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRouteRoute,
} as any)

const PrivateLayoutIndexRoute = PrivateLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateLayoutRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRoute
    }
    '/_private/_layout': {
      id: '/_private/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof PrivateRouteImport
    }
    '/_private/_layout/': {
      id: '/_private/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutIndexImport
      parentRoute: typeof PrivateLayoutRouteImport
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginIndexImport
      parentRoute: typeof PublicRouteImport
    }
  }
}

// Create and export the route tree

interface PrivateLayoutRouteRouteChildren {
  PrivateLayoutIndexRoute: typeof PrivateLayoutIndexRoute
}

const PrivateLayoutRouteRouteChildren: PrivateLayoutRouteRouteChildren = {
  PrivateLayoutIndexRoute: PrivateLayoutIndexRoute,
}

const PrivateLayoutRouteRouteWithChildren = PrivateLayoutRouteRoute._addFileChildren(PrivateLayoutRouteRouteChildren)

interface PrivateRouteRouteChildren {
  PrivateLayoutRouteRoute: typeof PrivateLayoutRouteRouteWithChildren
}

const PrivateRouteRouteChildren: PrivateRouteRouteChildren = {
  PrivateLayoutRouteRoute: PrivateLayoutRouteRouteWithChildren,
}

const PrivateRouteRouteWithChildren = PrivateRouteRoute._addFileChildren(PrivateRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(PublicRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PrivateLayoutRouteRouteWithChildren
  '/': typeof PrivateLayoutIndexRoute
  '/login': typeof PublicLoginIndexRoute
}

export interface FileRoutesByTo {
  '': typeof PublicRouteRouteWithChildren
  '/': typeof PrivateLayoutIndexRoute
  '/login': typeof PublicLoginIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_private': typeof PrivateRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_private/_layout': typeof PrivateLayoutRouteRouteWithChildren
  '/_private/_layout/': typeof PrivateLayoutIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/' | '/login'
  id: '__root__' | '/_private' | '/_public' | '/_private/_layout' | '/_private/_layout/' | '/_public/login/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrivateRouteRoute: typeof PrivateRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PrivateRouteRoute: PrivateRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/_public"
      ]
    },
    "/_private": {
      "filePath": "_private/route.tsx",
      "children": [
        "/_private/_layout"
      ]
    },
    "/_public": {
      "filePath": "_public/route.tsx",
      "children": [
        "/_public/login/"
      ]
    },
    "/_private/_layout": {
      "filePath": "_private/_layout/route.tsx",
      "parent": "/_private",
      "children": [
        "/_private/_layout/"
      ]
    },
    "/_private/_layout/": {
      "filePath": "_private/_layout/index.tsx",
      "parent": "/_private/_layout"
    },
    "/_public/login/": {
      "filePath": "_public/login/index.tsx",
      "parent": "/_public"
    }
  }
}
ROUTE_MANIFEST_END */
