# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy via ssh

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: echo "VITE_API_BASE_URL=${{vars.API_BASE_URL}}" >> .env.local
      - run: bun run build

      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /var/www/html/dari_tour_admin_front
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: root
          remote_key: ${{ secrets.DEPLOY_KEY }}
